name: Issue Report
description: File a issue report
title: ""
labels: ["\U00002611 검토요청"]
projects: []
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: Type
    attributes:
      label: Type
      description: What version of our software are you running?
      options:
        - 기능 추가 (Default)
        - 리팩토링
        - 버그 수정
        - 컨벤션 수정
        - 테스트
      default: 0
    validations:
      required: true
  - type: input
    id: 구현 목표
    attributes:
      label: 구현 목표
      description: 새로운 작업에 대한 명확하고 간결하게 설명을 작성한다.
      placeholder: 이 기능을 통해 해결하고자 하는 동기나 문제를 설명. ex) 프로젝트나 사용자에게 어떤 이점이 있는가?
    validations:
      required: false
  - type: textarea
    id: 세부 작업
    attributes:
      label: 세부 작업
      description: 작업에 대한 상세한 설명
      placeholder: 작업에 대한 상세한 설명을 작성한다.
      value: "- [ ] 세부 작업 1: "
    validations:
      required: true
  
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
