name: 'Issue Request'
description: 

body:
  - type: dropdown
    id: type
    attributes:
      label: 작업 종류
      options:
        - 기능 추가
        - 리팩터링
        - 버그 수정
        - 컨벤션 수정
        - 테스트
      multiple: true

  - type: textarea
    id: goal
    attributes:
      label: 작업 목표
      description: 새로운 작업에 대한 명확하고 간결할 설명을 작성해주세요. 이 작업을 통해 해결하고자 하는 동기나 문제를 설명하면 좋아요.
    validations:
      required: true

  - type: textarea
    id: detail
    attributes:
      label: 세부 작업
      description: 작업에 대한 상세한 설명을 작성해주세요.
            
    validations:
      required: true

  - type: textarea
    id: remark
    attributes:
      label: 특이사항
      description: 작업 계획 및 특이사항을 작성해주세요. 참고하면 좋을 내용을 추가해도 좋아요.
    validations:
      required: true
