FROM        ubuntu:20.04
MAINTAINER  KEEMSY <ahr03003@gmail.com>

ARG     DEBIAN_FRONTEND=noninteractive
ENV     TZ=Asia/Seoul

########################################################################################
# Set docker container
########################################################################################
# for apt error
RUN     echo "Acquire::Check-Valid-Until \"false\";\nAcquire::Check-Date \"false\";" | cat > /etc/apt/apt.conf.d/10no--check-valid-until

RUN     apt-get update && apt-get -y upgrade
RUN     apt-get install -y build-essential locales tzdata vim wget git curl cron rsync net-tools openssh-server
RUN     locale-gen en_US.UTF-8


########################################################################################
# Run Shell Script
########################################################################################
COPY    run.sh /run.sh
RUN     chmod +x /run.sh